package com.zilizero.app.network

import java.net.URLEncoder
import java.security.MessageDigest

/**
 * Implementation of Bilibili Wbi Signing Algorithm (v2024-2025).
 * Based on reverse engineering report.
 */
object WbiUtil {

    private val MIXIN_KEY_ENC_TAB = intArrayOf(
        46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49,
        33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13, 37, 48, 7, 16, 24, 55, 40,
        61, 26, 17, 0, 1, 60, 51, 30, 4, 22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11,
        36, 20, 34, 44, 52
    )

    /**
     * Extracts the raw key from the URL.
     * Example: https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png -> 7cd084941338484aae1ad9425b84077c
     */
    private fun extractKey(url: String): String {
        return url.substringAfterLast("/").substringBefore(".")
    }

    /**
     * Generates the Mixin Key from img_key and sub_key.
     */
    fun getMixinKey(imgUrl: String, subUrl: String): String {
        val imgKey = extractKey(imgUrl)
        val subKey = extractKey(subUrl)
        val rawKey = imgKey + subKey
        
        val sb = StringBuilder()
        for (i in 0 until 32) {
            if (i < MIXIN_KEY_ENC_TAB.size) {
                 val index = MIXIN_KEY_ENC_TAB[i]
                 if (index < rawKey.length) {
                     sb.append(rawKey[index])
                 }
            }
        }
        return sb.toString()
    }

    /**
     * Signs the parameters.
     * 
     * @param params Original query parameters
     * @param mixinKey The key generated by getMixinKey
     * @return A map containing all original params plus 'wts' and 'w_rid'
     */
    fun signParams(params: Map<String, String>, mixinKey: String): Map<String, String> {
        val currTime = System.currentTimeMillis() / 1000
        val newParams = params.toMutableMap()
        newParams["wts"] = currTime.toString()

        // Sort keys
        val sortedKeys = newParams.keys.sorted()
        
        // Build query string (RFC 3986 encoding)
        val queryBuilder = StringBuilder()
        for ((index, key) in sortedKeys.withIndex()) {
            val value = newParams[key] ?: ""
            // Filter specific characters (simple implementation based on report)
            if (key.length > 32) continue // Safety check, though not strictly in report
            
            val encodedValue = encodeURIComponent(value)
            if (index > 0) {
                queryBuilder.append("&")
            }
            queryBuilder.append(key).append("=").append(encodedValue)
        }

        // Add salt (mixin_key) WITHOUT '&'
        val stringToSign = queryBuilder.toString() + mixinKey
        
        // MD5 Hash
        val wRid = md5(stringToSign)
        
        newParams["w_rid"] = wRid
        return newParams
    }

    private fun encodeURIComponent(s: String): String {
        return URLEncoder.encode(s, "UTF-8")
            .replace("+", "%20")
            .replace("*", "%2A")
            .replace("%7E", "~")
    }

    private fun md5(input: String): String {
        val md = MessageDigest.getInstance("MD5")
        val digest = md.digest(input.toByteArray())
        return digest.joinToString("") { "%02x".format(it) }
    }
}
